name: seuchida
description: "한국형 TikTok+Pinterest+BeReal 느낌의 랜덤 이미지 릴스 앱"
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^0.13.6
  cached_network_image: ^3.2.3
  lottie: ^2.3.2
  google_mobile_ads: ^5.1.0
  purchases_flutter: ^6.22.0
  permission_handler: ^11.3.1
  gallery_saver: ^2.3.2
  page_transition: ^2.1.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/like.json
